/* Boilerplate auto-generated by MMZK1526 */

#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "mmzktestbase.h"

static void float_test(void) {
	float x = 3.0, y = 3.0, z = 3.01;
	double a = 3.0, b = 3.0, c = 3.01;
	mmzk_assert_pop_caption("Test float:\n");
	mmzk_assert_equal_float(x, y, 0.001, "\tExact: ");
	mmzk_assert_equal_float(x, z, 0.1, "\tAllow Big Error: ");
	mmzk_assert_equal_float(x, z, 0.001, "\tAllow Tiny Error: ");
	mmzk_assert_pop_caption("\n");

	mmzk_assert_pop_caption("Test double:\n");
	mmzk_assert_equal_double(a, b, 0.001, "\tExact: ");
	mmzk_assert_equal_double(a, c, 0.1, "\tAllow Big Error: ");
	mmzk_assert_equal_double(a, c, 0.001, "\tAllow Tiny Error: ");
	mmzk_assert_pop_caption("\n");
}

void floattest_summary(void) {
	mmzk_test_summary(float_test, "Float Test:\n");
}

#ifdef TEST_MAIN

int main(int argc, char **argv) {
	return mmzk_test_report(&floattest_summary, argc, argv);
}

#endif /* TEST MAIN */
