/* Boilerplate auto-generated by MMZK1526 */

#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "mmzktestbase.h"

static void foo_test(void) {
	mmzk_assert_pop_caption("Test int:\n");
	mmzk_assert_equal_int8(3, 3, "\tInt 8: ");
	mmzk_assert_equal_int16(3, 3, "\tInt 16: ");
	mmzk_assert_equal_int32(3, 3, "\tInt 32: ");
	mmzk_assert_equal_int64(3, 3, "\tInt 64: ");
	mmzk_assert_pop_caption("\n");

	mmzk_assert_pop_caption("Test uint:\n");
	mmzk_assert_equal_uint8(3, 3, "\tUnsigned Int 8: ");
	mmzk_assert_equal_uint16(3, 3, "\tUnsigned Int 16: ");
	mmzk_assert_equal_uint32(3, 3, "\tUnsigned Int 32: ");
	mmzk_assert_equal_uint64(3, 3, "\tUnsigned Int 64: ");
	mmzk_assert_pop_caption("\n");
}

static void bar_test(void) {
	mmzk_assert_pop_caption("Test char:\n");
	mmzk_assert_equal_char('c', 'c', "\t'c' == 'c': ");
	mmzk_assert_pop_caption("\n");

	mmzk_assert_pop_caption("Test bool:\n");
	mmzk_assert_true(1, "\ttrue: ");
	mmzk_assert_equal_bool(false, 0, "\tbool: ");
	mmzk_assert_pop_caption("\n");
}

void test_summary(void) {
	mmzk_test_summary(foo_test, "Foo:\n");
	mmzk_test_summary(bar_test, "Bar:\n");
}

#ifdef TEST_MAIN

int main(int argc, char **argv) {
	return mmzk_test_report(&test_summary, argc, argv);
}

#endif /* TEST MAIN */
