/* Boilerplate auto-generated by MMZK1526 */

#ifndef MMZK1526
#define MMZK1526
#endif /* MMZK1526 */

#ifndef TESTSUITE_H
#define TESTSUITE_H

extern void floattest_summary(void);
extern void integraltest_summary(void);

#endif /* TESTSUITE_H */
